version: '3'
volumes:
    npm-data:
    npm-ssl:
    npm-db:
networks:
       frontend:
        external: true
       backend:
        external: true
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "admin"
      DB_MYSQL_PASSWORD: "2p3vcAdmin"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    networks:
      - frontend
      - backend
  npm-db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '2p3vcAdmin'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '2p3vcAdmin'
    volumes:
      - npm-db:/var/lib/mysql
    networks:
      - backend